### ISSUE TITLE
Error when casile setup 

### ISSUE THREAD

**Issue by jiucenglou** [sile-typesetter/casile-template#1]
After I downloaded zip file, unzipped, `git init`, `casile setup` fails. Could you suggest how to fix ? Many thanks !
```
(base) user@localhost:~/Downloads/casile-template-master$ casile setup
⛫ Welcome to CaSILE ⁨v0.13.1⁩!                                                                                              ⟳ Configuring repository for use with CaSILE.
✔ Everything seems to be ship shape, warm up the presses!
⟳ Building target(s) using ‘make’.                                                                                        thread 'main' panicked at src/status/mod.rs:130:46:
called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 4, message: "revspec 'HEAD' not found" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) user@localhost:~/Downloads/casile-template-master$ 
```

**Comment by jiucenglou** [comment]
run with `RUST_BACKTRACE=1` environment variable does not provide extra information

```
(base) user@localhost:~/Downloads/casile-template-master$ RUST_BACKTRACE=1 casile -d setup
⛫ Welcome to CaSILE ⁨v0.13.1⁩!                                                                                              ⟳ Configuring repository for use with CaSILE.
Is the path a Git repository? Yes
✔ Everything seems to be ship shape, warm up the presses!
Is the path a Git repository? Yes
Is the system’s ‘make’ executable? Yes
Are we safely outside of the CaSILE source repository? Yes
Can we write to the project base directory? Yes
Is the system’s ‘make’ a supported version of GNU Make? Yes
⟳ Building target(s) using ‘make’.                                                                                        thread 'main' panicked at src/status/mod.rs:130:46:
called `Result::unwrap()` on an `Err` value: Error { code: -3, klass: 4, message: "revspec 'HEAD' not found" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
(base) user@localhost:~/Downloads/casile-template-master$ 
```

**Comment by alerque** [comment]
This is an interesting case I didn't setup CaSILE to handle. I would have suggested using `git clone` to start with the template repo. Using the ZIP download is okay, but as you noted you have to initialize a Git repository yourself. CaSILE has a hard prerequisite that projects are tracked in Git.

You ran `git init`, but you repository still has no commits. Apparently some of the things `casile` needs require that it can inspect the history. It is complaining that there is no `HEAD` in the repository, which means you don't have even a single commit and hence it can't figure out where it is in life.

I'll add check for that specifically so it gives a more intelligible error message.
